CC = gcc
FLAGS = -g -O0 -o

all : bubble_sort bubble_sort_user_input selection_sort insertion_sort quick_sort

%.o : %.c 
	$(CC) $(FLAGS) $^
clean :
	rm -rf *.o bubble_sort bubble_sort_user_input selection_sort insertion_sort quick_sort
