
#this is makefile

outfile: main.o add_begin.o add_end.o print.o rev_print.o rev_data.o 
	cc main.c add_begin.c add_end.c print.c rev_print.c rev_data.c

main.o:main.c 
	cc -c main.c
add_begin.o:add_begin.c
	cc -c add_begin.c
add_end.o:add_end.c
	cc -c add_end.c
print.o:print.c
	cc -c print.c
rev_print.o:rev_print.c
	cc -c rev_print.c
rev_data.o:rev_data.c
	cc -c rev_data.c
